Script started on 2020-10-19 22:34:05-04:00 [TERM="xterm-256color" TTY="/dev/pts/20" COLUMNS="180" LINES="52"]
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ date
Mon 19 Oct 2020 10:34:20 PM EDT
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ who am i
ahemmin  pts/63       2020-10-19 22:34
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ ls
ahemmin_Asn3part3.script  [0m[38;5;40ma.out[0m  [38;5;40masn3a[0m  asn3a.c  [38;5;40masn3b[0m  asn3b.c
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ exit[K[K[K[Kgcc asn3a.c -o asn3a
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ gcc asn3b.c -o asn3b
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ ./a.out

Size of Array: 40 bytes
Length of Array: 10 elements

PART 1: 
The values stored into the array are : 
12 63 44 89 3 55 73 27 37 18 

PART 2:
The values stored into the array in reverse are : 
18 37 27 73 55 3 89 44 63 12 

PART 3:
The smallest value stored in the array is :
value: 3 at the 5th position from the left

PART 4:
The sum (total) value of the array is : 12 + 63 + 44 + 89 + 3 + 55 + 73 + 27 + 37 + 18  equals: 421 

PART 5:
Copy the array into a new array, but in reverse order :
Original array :
 12 63 44 89 3 55 73 27 37 18 
New (Reversed) array :
 18 37 27 73 55 3 89 44 63 12 

PART 6:
Switch the first value in the array with the last value in the array :
Original array :
 12 63 44 89 3 55 73 27 37 18 
Changed array :
 18 63 44 89 3 55 73 27 37 12

PART 7:
Sort the array in ascending order :
Original array :
 12 63 44 89 3 55 73 27 37 18 
Changed array :
 3 12 18 27 37 44 55 63 73 89 

]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ ./asn3a

Size of Array: 60 bytes
Length of Array: 15 elements

PART 1: 
The values stored into the array are : 
12 63 44 89 3 55 73 27 37 18 14 24 30 52 69 

PART 2:
The values stored into the array in reverse are : 
69 52 30 24 14 18 37 27 73 55 3 89 44 63 12 

PART 3:
The smallest value stored in the array is :
value: 3 at the 5th position from the left

PART 4:
The sum (total) value of the array is : 12 + 63 + 44 + 89 + 3 + 55 + 73 + 27 + 37 + 18 + 14 + 24 + 30 + 52 + 69  equals: 610 

PART 5:
Copy the array into a new array, but in reverse order :
Original array :
 12 63 44 89 3 55 73 27 37 18 14 24 30 52 69 
New (Reversed) array :
 69 52 30 24 14 18 37 27 73 55 3 89 44 63 12 

PART 6:
Switch the first value in the array with the last value in the array :
Original array :
 12 63 44 89 3 55 73 27 37 18 14 24 30 52 69 
Changed array :
 69 63 44 89 3 55 73 27 37 18 14 24 30 52 12

PART 7:
Sort the array in ascending order :
Original array :
 12 63 44 89 3 55 73 27 37 18 14 24 30 52 69 
Changed array :
 3 12 14 18 24 27 30 37 44 52 55 63 69 73 89 

]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ ./a.[Ksnb[K3b
Input? 3
The final total is: 5
Input? 4
The final total is: 5
Input? 5
The final total is: 10
Input? 6
The final total is: 10
Input? 7
The final total is: 17
Input? 1
The final total is: 0
Input? 0
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ mv asn3a.c ahemming[K_asn3.[Ka.c
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ mv asn3b.c ahemmin_asn3b.c
]0;ahemmin@compute:~/courses/cs2211a/Asn/asn3[ahemmin@compute asn3]$ exit
exit

Script done on 2020-10-19 22:39:03-04:00 [COMMAND_EXIT_CODE="0"]
